CREATE TABLE Usuario (
idUsuario INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
Nombre VARCHAR(100) NOT NULL,
Contrasena VARCHAR(100) NOT NULL,
Correo VARCHAR(100) NOT NULL
);

CREATE TABLE Viaje (
idViaje INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
Destino VARCHAR(100) NOT NULL,
Fecha VARCHAR(100) NOT NULL
);

CREATE TABLE ViajeUsuario(
idViajeUsuario INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
fkDestino INTEGER NOT NULL,
fkUsuario INTEGER NOT NULL,
CONSTRAINT FOREIGN KEY(fkDestino) REFERENCES Destino(idDestino),
CONSTRAINT FOREIGN KEY(fkUsuario) REFERENCES Usuario(idUsuario)
);
SELECT * FROM proyecto.usuario;


SELECT * FROM proyecto.viaje;

INSERT INTO Viaje (Nombre, Destino, Fecha)
VALUES ('Viaje1', 'Boyacá', '15/7/2021' );

SET FOREIGN_KEY_CHECKS=0;

TRUNCATE TABLE proyecto.viaje;

SET FOREIGN_KEY_CHECKS=1;

SET FOREIGN_KEY_CHECKS=0;

SET FOREIGN_KEY_CHECKS=1;



